version: '3.3'

services:
  api:
    image: api
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/src/app
    ports:
      - '3001:3001'
  client:
    environment:
      REACT_APP_API_BASE: http://localhost:3001/api/
    image: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/client
    ports:
      - '3000:3000'
    stdin_open: true
