version: '3.3'

services:
  api:
    env_file:
      - ./server/.env
    image: api
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - './server:/src'
    ports:
      - '3001:3001'
    stdin_open: true
  client:
    env_file:
      - ./client/.env
    image: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - './client:/src'
    ports:
      - '3000:3000'
    stdin_open: true
